appName: metrics-app
replicaCount: 1

deployment:
  name: "metrics-app-deployment"
  container:
    name: "metrics-app-container"
    image:
      repository: "ghcr.io/cloudraftio/metrics-app"
      tag: "1.1"
  secretName: "metrics-app-secret"

ingress:
  name: "metrics-app"

service:
  name: "metrics-app"
  type: "ClusterIP"
  port: 8080

secret:
  name: "metrics-app-secret"
  data:
    METRICS_APP_PASSWORD: "dummy"