apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default "metrics-app-secret" }}
  namespace: {{ .Values.namespace | default "metrics-app-prod" }}
type: Opaque
data:
  PASSWORD: {{ .Values.secret.data.METRICS_APP_PASSWORD | b64enc | quote }}