apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default "metrics-app" }}
  namespace: {{ .Values.namespace | default "metrics-app-prod" }}
  labels:
    app: {{ .Values.appName | default "metrics-app" }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.appName | default "metrics-app" }}
